"""dbt preflight: warehouse-free CI for dbt pull requests.

Builds and tests the models a pull request changes against synthetic data generated by
model2data, checks house conventions, and produces one review comment. Nothing here needs
a warehouse credential.
"""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("dbt-preflight")
except PackageNotFoundError:  # a source tree that was never installed
    __version__ = "0.0.0+unknown"
