"""dbt preflight: warehouse-free CI for dbt pull requests.

Builds and tests the models a pull request changes against synthetic data generated by
model2data, checks house conventions, and produces one review comment. Nothing here needs
a warehouse credential.
"""

__version__ = "0.1.0"
